name: Laravel Local CI

on:
    push:
        branches: [ "main" ]   # mainブランチにpushされたとき
    pull_request:
        branches: [ "main" ]   # mainブランチにPRが来たとき

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: mbstring, pdo_mysql, bcmath, intl
                  coverage: none

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Copy .env
              run: cp .env.example .env

            - name: Generate key
              run: php artisan key:generate

            - name: Run migrations
              run: php artisan migrate --force

            - name: Run tests
              run: php artisan test